del /F/S/Q *.bak
del /F/S/Q *.aux
del /F/S/Q *.dvi
del /F/S/Q *.log
del /F/S/Q *.???~
del /F/S/Q *.out
del /F/S/Q *.pdf
del /F/S/Q *.toc
del /F/S/Q *.cut
del /F/S/Q *.lof
del /F/S/Q *.lot
del /F/S/Q *.bbl
del /F/S/Q *.blg
del /F/S/Q *.thm
del /F/S/Q *.lst
del /F/S/Q *.sty
del /F/S/Q ctextemp*
del /F/S/Q *.ps
del /F/S/Q *.tmp
del /F/S/Q *idx